version = 0.1
[default]
[default.build]
[default.build.parameters]
cached=true
parallel=true
use_container=true

[default.local_invoke]
[default.local_invoke.parameters]
env_vars="locals.json"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
env_vars="locals.json"

[default.local_start_api]
[default.local_start_api.parameters]
env_vars="locals.json"
warm_containers="EAGER"